#!/bin/bash

#/home/bastian/projects/angler/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -c fixup.S -o fixup.o
#objcopy -O binary fixup.o fixup.bin


KPATH=/home/bastian/projects/angler/mainline-kernel/arch/arm64/boot/
DTBPATH=${KPATH}dts/qcom/

cat ${KPATH}Image.gz ${DTBPATH}msm8994-angler-rev-101.dtb > Image.gz-dtb


mkbootimg --output boot.img \
         --kernel Image.gz-dtb \
         --ramdisk initrd.img \
         --cmdline "msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 boot_cpus=0-3 console=ttyMSM0,115200n8 earlycon=msm_serial_dm,0xf991e000 root=/dev/ram rw rdinit=/bin/sh" \
         --base 0 --pagesize 2048
         
         
#--cmdline "msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 boot_cpus=0-3 console=ttyMSM0,115200n8 earlycon=msm_serial_dm,0xf991e000" 
#--cmdline "msm_rtb.filter=0x37 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 boot_cpus=0-3 console=ttyHSL0,115200,n8 earlyprintk=msm_hsl_uart,0xf991e000"
